Stop using Advertising Id in track and match requests
velocidi/velocidi-android-sdk pull request #39
Opened 2021-03-08 17:44 UTC by dimamo5

Depends on #38 

Fetching and using the Advertising Id implicitly on `track` and `match` requests may lead the client app to break some privacy rules. It is also problematic on devices that don't use Google services or in devices with have stricter privacy settings. To avoid dealing with such issues we decided to shift the responsibility of using Google's Advertising Id to the client app.

So, this PR changes the `track` method to accept an `UserId` and stops fetching the Advertising Id on `init` and using it on track and match requests.

2021-03-08 22:35 UTC, silva95gustavo approved these changes

2021-03-10 12:02 UTC, thyandrecardoso requested changes

2021-03-10 12:02 UTC, thyandrecardoso commented on velocidi-sdk/src/test/kotlin/com/velocidi/VelocidiTest.kt
> +            listOf(UserId("123"), UserId("mail@example.com", "eml"))
Nitpick: can we remove literal email examples? This example in particular is not consistent with the id _type_ and I think we should avoid exemplifying plain emails... Can we use a proper sha256 example here and in other examples?

2021-03-10 14:19 UTC, dimamo5 commented on velocidi-sdk/src/main/kotlin/com/velocidi/UserId.kt
> +data class UserId(val id: String, val type: String = "gaid") {
Fixed in f19f929

2021-03-10 14:20 UTC, dimamo5 commented on velocidi-sdk/src/main/kotlin/com/velocidi/Velocidi.kt
>      fun match(providerId: String, userIds: List<UserId>) {
Done in 87c2b67

2021-03-11 10:29 UTC, thyandrecardoso approved these changes

2021-03-11 10:30 UTC, thyandrecardoso commented
Looks good. Waiting on the approval from @silva95gustavo.

2021-03-11 10:38 UTC, merged

2021-03-11 11:48 UTC, silva95gustavo commented
Good job @dimamo5!